name: Build Release

on:
  release:
    types: [published]

jobs:
  zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zip dist
        run: |
          cd dist
          zip -r ../ThreadsTracker.zip .

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: ThreadsTracker.zip